publisher:
    image: csarcom/python-pubsub
    command: gunicorn -b 0.0.0.0:8000 example.publisher:app
    environment:
        - PYTHONUNBUFFERED=0
    ports:
        - "8000:8000"
    links:
        - rabbitmq
    volumes:
        - ./:/app
subscriber:
    image: csarcom/python-pubsub
    command: python example/subscriber.py
    environment:
        - PYTHONUNBUFFERED=0
    links:
        - rabbitmq
    volumes:
        - ./:/app
rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"
