rabbitmq:
    publisher:
        connection:
            failover_strategy: round-robin
            connect_timeout: 5
            transport_options:
                confirm_publish: True

        exchange:
            name: python-pubsub
            type: direct
            durable: True
            auto_delete: False

        publish:
            routing_key: pubsub
            serializer: json
            compression: zlib
            retry: True

    subscriber:
        connection:
            connect_timeout: 5

        exchange:
            name: python-pubsub
            type: direct
            durable: True
            auto_delete: False

        queue:
            routing_key: pubsub

        consumer:
            accept:
                - json
